# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=800)),
                ('body', models.TextField()),
            ],
        ),
    ]
