# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160604_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
